baseURL = 'https://yourusername.github.io/kona-blog'
languageCode = 'en-us'
title = 'Kona Adventures'
theme = 'ananke'

[params]
  description = "Adventures and memories from my trip to Kona, Hawaii"
  keywords = ["travel", "hawaii", "kona", "photography", "adventure"]
  images = ["images/kona-cover.jpg"]
  
  [params.author]
    name = "Your Name"
    email = "your.email@example.com"
    
  [params.social]
    github = "yourusername"
    
  [params.search]
    enable = true
    
  [params.docs]
    enable = false
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true